### ISSUE TITLE
Ping Pong

### ISSUE THREAD

**Issue by freamon** [DeGuitard/anime-cli#1]
Rizon's first PING challenge is too soon to join channel
JOIN attempt is not recognised by server, but `has_joined` is set to true, so never re-attempted
Can be fixed by moving `has_joined=true` into `JOIN_REGEX.is_match` block

Rizon's second PING challenge is not alphanumberic (typically something like PING :irc.rizon.net)
PING_REGEX isn't matched, so can lead to timeout
Can be fixed by changing `PING_REGEX` to `"PING :.*"`

PING challenges aren't neccessarily an ideal time to join channel
Either too soon to be recognized, or minutes later
Could be improved by adding extra REGEX from when user's MODE is set, e.g.
`static ref MODE_REGEX: Regex = Regex::new(r#"MODE .* :\+.*"#).unwrap();`
and adding a block to JOIN when it is matched

**Comment by exKitsune** [comment]
@freamon If you're interested, I've forked and updated this tool
